// flow-typed signature: f9884017505131f2c9bdf284a1f0f064
// flow-typed version: <<STUB>>/debowerify_v^1.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debowerify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debowerify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'debowerify/index' {
  declare module.exports: $Exports<'debowerify'>;
}
declare module 'debowerify/index.js' {
  declare module.exports: $Exports<'debowerify'>;
}
