// flow-typed signature: 6f37da15690d83edd87d1603041ffa2b
// flow-typed version: <<STUB>>/exhibit-plugin-rollup_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exhibit-plugin-rollup/resolveAsDirectory' {
  declare module.exports: any;
}

declare module 'exhibit-plugin-rollup/resolveAsFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exhibit-plugin-rollup/index' {
  declare module.exports: $Exports<'exhibit-plugin-rollup'>;
}
declare module 'exhibit-plugin-rollup/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-rollup'>;
}
declare module 'exhibit-plugin-rollup/resolveAsDirectory.js' {
  declare module.exports: $Exports<'exhibit-plugin-rollup/resolveAsDirectory'>;
}
declare module 'exhibit-plugin-rollup/resolveAsFile.js' {
  declare module.exports: $Exports<'exhibit-plugin-rollup/resolveAsFile'>;
}
