// flow-typed signature: dcc056487b1f24b0320ed8d7a46182bb
// flow-typed version: <<STUB>>/exhibit-directory_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-directory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-directory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-directory/index' {
  declare module.exports: $Exports<'exhibit-directory'>;
}
declare module 'exhibit-directory/index.js' {
  declare module.exports: $Exports<'exhibit-directory'>;
}
