// flow-typed signature: 657ae8098e108699d86ef5cadd0d433a
// flow-typed version: <<STUB>>/exhibit-plugin-serve_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exhibit-plugin-serve/client/client.entry' {
  declare module.exports: any;
}

declare module 'exhibit-plugin-serve/compileRedirect' {
  declare module.exports: any;
}

declare module 'exhibit-plugin-serve/injectSnippet' {
  declare module.exports: any;
}

declare module 'exhibit-plugin-serve/parseRedirects' {
  declare module.exports: any;
}

declare module 'exhibit-plugin-serve/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exhibit-plugin-serve/client/client.entry.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve/client/client.entry'>;
}
declare module 'exhibit-plugin-serve/compileRedirect.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve/compileRedirect'>;
}
declare module 'exhibit-plugin-serve/index' {
  declare module.exports: $Exports<'exhibit-plugin-serve'>;
}
declare module 'exhibit-plugin-serve/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve'>;
}
declare module 'exhibit-plugin-serve/injectSnippet.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve/injectSnippet'>;
}
declare module 'exhibit-plugin-serve/parseRedirects.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve/parseRedirects'>;
}
declare module 'exhibit-plugin-serve/types.js' {
  declare module.exports: $Exports<'exhibit-plugin-serve/types'>;
}
