// flow-typed signature: aed33b88959dbc92f51e44b8f1d0339b
// flow-typed version: <<STUB>>/exhibit_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exhibit/cache' {
  declare module.exports: any;
}

declare module 'exhibit/compose' {
  declare module.exports: any;
}

declare module 'exhibit/createMatcher' {
  declare module.exports: any;
}

declare module 'exhibit/diff' {
  declare module.exports: any;
}

declare module 'exhibit/normalize' {
  declare module.exports: any;
}

declare module 'exhibit/subset' {
  declare module.exports: any;
}

declare module 'exhibit/withSubset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exhibit/cache.js' {
  declare module.exports: $Exports<'exhibit/cache'>;
}
declare module 'exhibit/compose.js' {
  declare module.exports: $Exports<'exhibit/compose'>;
}
declare module 'exhibit/createMatcher.js' {
  declare module.exports: $Exports<'exhibit/createMatcher'>;
}
declare module 'exhibit/diff.js' {
  declare module.exports: $Exports<'exhibit/diff'>;
}
declare module 'exhibit/index' {
  declare module.exports: $Exports<'exhibit'>;
}
declare module 'exhibit/index.js' {
  declare module.exports: $Exports<'exhibit'>;
}
declare module 'exhibit/normalize.js' {
  declare module.exports: $Exports<'exhibit/normalize'>;
}
declare module 'exhibit/subset.js' {
  declare module.exports: $Exports<'exhibit/subset'>;
}
declare module 'exhibit/withSubset.js' {
  declare module.exports: $Exports<'exhibit/withSubset'>;
}
