// flow-typed signature: 5bfec0212d93d1b910095414d5539cd1
// flow-typed version: <<STUB>>/exhibit-plugin-sass_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-plugin-sass/index' {
  declare module.exports: $Exports<'exhibit-plugin-sass'>;
}
declare module 'exhibit-plugin-sass/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-sass'>;
}
