// flow-typed signature: 9ee89155c33a6c126a4464ba00e9ada0
// flow-typed version: <<STUB>>/exhibit-plugin-gulp_v^0.12.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-gulp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-gulp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-plugin-gulp/index' {
  declare module.exports: $Exports<'exhibit-plugin-gulp'>;
}
declare module 'exhibit-plugin-gulp/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-gulp'>;
}
