// flow-typed signature: 736515ef648096927d7bf9ae429551a6
// flow-typed version: <<STUB>>/glob-promise_v^3.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glob-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glob-promise/lib/index.js' {
  declare module.exports: $Exports<'glob-promise/lib/index'>;
}
