// flow-typed signature: 9b673990b247255f1785184c5a1898ed
// flow-typed version: <<STUB>>/rollup-plugin-bower-resolve_v^0.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-bower-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-bower-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-bower-resolve/dist/bower' {
  declare module.exports: any;
}

declare module 'rollup-plugin-bower-resolve/dist/rollup-plugin-bower-resolve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-bower-resolve/dist/bower.js' {
  declare module.exports: $Exports<'rollup-plugin-bower-resolve/dist/bower'>;
}
declare module 'rollup-plugin-bower-resolve/dist/rollup-plugin-bower-resolve.js' {
  declare module.exports: $Exports<'rollup-plugin-bower-resolve/dist/rollup-plugin-bower-resolve'>;
}
