// flow-typed signature: d7f6480c77b982745e5c1a9537618b65
// flow-typed version: <<STUB>>/trip_v^1.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trip/cli' {
  declare module.exports: any;
}

declare module 'trip/dist/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trip/cli.js' {
  declare module.exports: $Exports<'trip/cli'>;
}
declare module 'trip/dist/lib/index.js' {
  declare module.exports: $Exports<'trip/dist/lib/index'>;
}
